project:
  type: website

website:
  title: "Joann Jun"
  navbar:
    background: (#FFF8DC)
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      #  text: About
      - href: projects.qmd
        text: Projects
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/joann-jun/
        target: blank
      - icon: github
        href: https://github.com/joannjun
        target: blank
      - icon: file-earmark-person
        href: assets/Resume.pdf
        target: blank

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


execute:
  freeze: auto
  
